name = "droptop-api"
main = "src/index.js"
workers_dev = false
compatibility_date = "2025-09-15"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[durable_objects.bindings]]
name = "MONGODB_DURABLE_OBJECT"
class_name = "MongoDBDurableConnector"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["MongoDBDurableConnector"]